spring:
    application:
      name: indra-challenge
    h2:
      console:
        enabled: true
    datasource:
      driver-class-name: org.postgresql.Driver
      username: postgres
      url: jdbc:postgresql://localhost:5432/indradb
      password: 123
    jpa:
      hibernate:
        ddl-auto: create-drop
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

logging:
  level:
    org:
      springframework:
        security: DEBUG


